### PR TITLE
Created package.json

### PR DESCRIPTION
**Pull request by MarkLeMerise**
This file will allow folks to install this package via NPM. It reflects everything in bower.json plus a `repository` field.

### CODE REVIEW

**Comment by kdela** [comment]
+1 @signalrcoreteam

**Comment by tjoskar** [comment]
+1 For this (and maybe renaming the repo).

**Comment by brndusic** [comment]
+1

**Comment by scottaddie** [comment]
This PR doesn't seem to be gaining any traction, so I wrote up my approach to solving the problem with npm. Read more [here](https://scottaddie.com/2016/07/19/an-npm-compatible-life-raft-for-signalr-javascript-client-installation/). Hopefully this helps some of you in the meantime.

**Comment by muratg** [comment]
Thanks! I'd like to take this one in and push an "official" npm package.  @MarkLeMerise if you're still active, could you bump the version to 2.2.1?  if not, I can handle it.

@Eilon can you check if the CLA was signed properly?

cc @DamianEdwards.

**Comment by muratg** [comment]
Looks like @MarkLeMerise deleted his original branch.  

I'll take this in a separate PR.

**Comment by scottaddie** [comment]
@muratg I'm willing to submit a PR for this `package.json` file. Sound good?

**Comment by muratg** [comment]
@scottaddie Sure, please do! Thanks.

**Comment by scottaddie** [comment]
@muratg PR submitted

**Comment by MarkLeMerise** [comment]
Sorry about that, guys. Thanks for picking up the mantle @scottaddie!

**Pull request closed without merging**
